MTL-3515 Remove Visa SRC from Demo page
bambora/na-payment-apis-demo pull request #103
Opened 2022-12-01 23:53 UTC by jgalvanbam

1.- Remove Visa SRC from Demo  page

2022-12-05 22:46 UTC, rb-bam requested changes

2022-12-05 22:46 UTC, rb-bam commented on README.md
> +We are using one test account on Pruduction in this demo app. All services can be tested on Production.
Production spelling error here.

2022-12-05 22:46 UTC, rb-bam commented on server/app/server.py
> +    secret_key = settings.secret_key
I don't understand why this is changed to pass a different settings value. Shouldn't this be changed to not pass in a second parameter?

2022-12-05 23:38 UTC, jgalvanbam commented on README.md
> +We are using one test account on Pruduction in this demo app. All services can be tested on Production.
Typo error fixed

2022-12-05 23:39 UTC, jgalvanbam commented on server/app/server.py
> +    secret_key = settings.secret_key
Variable removed and set to pass nothing as a second parameter.

2022-12-06 00:10 UTC, rb-bam approved these changes

2022-12-06 00:10 UTC, merged